-------------------------------------------------------------------------
-- Author:    John Fisher
-- Date:      int. blank
-- Purpose:   Create synonyms
-------------------------------------------------------------------------

CREATE PUBLIC SYNONYM PKG_ENC_CASUALTY_RESPONSE FOR PKG_ENC_CASUALTY_RESPONSE;
CREATE PUBLIC SYNONYM ENC_CASLTY_REQUEST FOR ENC_CASLTY_REQUEST;
CREATE PUBLIC SYNONYM ENC_CASLTY_RESPONSE FOR ENC_CASLTY_RESPONSE;
CREATE PUBLIC SYNONYM ENC_CASLTY_REQUEST_HIST FOR ENC_CASLTY_REQUEST_HIST;
CREATE PUBLIC SYNONYM ENC_CASLTY_RESPONSE_HIST FOR ENC_CASLTY_RESPONSE_HIST;
CREATE PUBLIC SYNONYM ENC_CASLTY_ERROR FOR ENC_CASLTY_ERROR;
CREATE PUBLIC SYNONYM ENC_CASLTY_ACK_CODES FOR ENC_CASLTY_ACK_CODES;
CREATE PUBLIC SYNONYM ENC_CASLTY_FILE_TRACKING FOR ENC_CASLTY_FILE_TRACKING;