-------------------------------------------------------------------------
-- Author:    John Fisher
-- Date:      int. blank
-- Purpose:   Grant required permissions
-------------------------------------------------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_REQUEST TO FISHEY_MAIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_RESPONSE TO FISHEY_MAIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_REQUEST_HIST TO FISHEY_MAIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_RESPONSE_HIST TO FISHEY_MAIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_ERROR TO FISHEY_MAIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_ACK_CODES TO FISHEY_MAIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_FILE_TRACKING TO FISHEY_MAIN;

GRANT SELECT ON ENC_CASLTY_REQUEST TO FISHEY_READ;
GRANT SELECT ON ENC_CASLTY_RESPONSE TO FISHEY_READ;
GRANT SELECT ON ENC_CASLTY_REQUEST_HIST TO FISHEY_READ;
GRANT SELECT ON ENC_CASLTY_RESPONSE_HIST TO FISHEY_READ;
GRANT SELECT ON ENC_CASLTY_ERROR TO FISHEY_READ;
GRANT SELECT ON ENC_CASLTY_ACK_CODES TO FISHEY_READ;
GRANT SELECT ON ENC_CASLTY_FILE_TRACKING TO FISHEY_READ;

GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_REQUEST TO FISHEY_OPER;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_RESPONSE TO FISHEY_OPER;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_REQUEST_HIST TO FISHEY_OPER;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_RESPONSE_HIST TO FISHEY_OPER;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_ERROR TO FISHEY_OPER;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_ACK_CODES TO FISHEY_OPER;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENC_CASLTY_FILE_TRACKING TO FISHEY_OPER;

GRANT EXECUTE ON PKG_ENC_CASUALTY_RESPONSE TO FISHEY_MAIN;
GRANT EXECUTE ON PKG_ENC_CASUALTY_RESPONSE TO FISHEY_OPER;
